# Welcome to Beautiful Jekyll!
remote_theme: "daattali/beautiful-jekyll"
title: "Emaleth's Playground"
author: "Emaleth"
navbar-links:
  Home: "/"
  Blog: "blog"
  About: "about"
  Contact: "contact"

avatar: "/assets/Red_Hood_Skull_50%.jpg"
round-avatar: true
social-network-links:
  github: "Emaleth"
  twitter: "EmalethDev"
  youtube: "channel/UCMWrvCUwZyBYuLbhGB6P-Cg"
  reddit: "EmalethDev"
  spotify: "j48c3mja372gszea3lklehgvq"
  itchio: "Emaleth"

rss-description: "This website is a virtual proof that I'm awesome"
share-links-active:
  twitter: true
  facebook: false
  linkedin: false
  vk: false

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

keywords: "game, gamedev, godot, github, Emaleth, entertainment"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"


date_format: "%H:%M %d-%m-%Y"
timezone: "Europe/Rome"
markdown: "kramdown"
highlighter: "rouge"
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: "GFM"

defaults:
  - # All
    scope:
      path: ""
    values:
      layout: "page"

  - # Posts
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false 
      social-share: true 
      readtime: true
 
  - # Pages
    scope:
      path: ""
      type: "pages"


      
exclude:
  - "CNAME"
  - "LICENSE"
  - "README.md"

include:
  - "_pages"

plugins:
  - "jekyll-remote-theme"
  - "jekyll-paginate"
  - "jekyll-sitemap"


